language: java

#jdk:
#    - oraclejdk8

addons:
 apt:
   packages:
   - ant
   - ant-optional

before_install:
  - pushd .
  - export BEAGLE_BRANCH=v4_release
  - mkdir -p ${BEAGLE_LIB}
  - git clone -b ${BEAGLE_BRANCH} https://github.com/beagle-dev/beagle-lib.git ${BEAGLE_BUILD}
  - cd ${BEAGLE_BUILD}
  - mkdir build
  - cd build
  - cmake -DBUILD_CUDA=OFF -DBUILD_OPENCL=OFF ..
  - make DESTDIR=${BEAGLE} install
  - export LD_LIBRARY_PATH=${BEAGLE_LIB}
  - ls ${BEAGLE_LIB}
  - popd

script:
  - ant dist
  - cd ci; ./test.sh
  - cd ..; ant -Djava.library.path=${BEAGLE_LIB} junit

env:
  global:
    - BEAGLE_BUILD=$HOME/beagle-build
    - BEAGLE=$HOME/beagle-lib
    - BEAGLE_LIB=${BEAGLE}/usr/local/lib
